#!/bin/bash
exit 1
cd "$(git rev-parse --show-toplevel)/makepkg"
file PKGBUILD
sed -i\~ s/'^pkgver=.*$'/'pkgver=0.1'/g PKGBUILD
diff -u0 PKGBUILD{\~,}
R="$?"
if [ "$R" -eq 1 ]; then
	rm -v PKGBUILD\~
	exit 0
else
	exit 1
fi
